# Generated by Django 5.2.1 on 2025-05-24 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email')])),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
